`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 2016/08/25 17:48:37
// Design Name: 
// Module Name: Trigger_Processor
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


module Trigger_Processor(
    input wire CLK_in,
    input wire CLK_Q40,
    input wire CLK_160,
    input wire CLK_320,
    input wire reset_in,
    
    input wire [4:0] LUT_init_data_in,
    input wire [14:0] LUT_init_Address_in,
    input wire LUT_init_flag_in,
    input wire [3:0] LUT_init_type_in,
    input wire [7:0] LUT_init_RoI_in,
    input wire [1:0] LUT_init_mode_in,
    input wire [14:0] LUT_rd_address_in,
    input wire [3:0] LUT_rd_type_in,
    input wire [7:0] LUT_rd_RoI_in,
    output wire [4:0] LUT_rd_data_out,
    
    input wire [6:0] BW_R0, 
    input wire [6:0] BW_R1, 
    input wire [6:0] BW_R2, 
    input wire [6:0] BW_R3, 
    input wire [6:0] BW_R4, 
    input wire [6:0] BW_R5, 
    input wire [6:0] BW_R6, 
    input wire [6:0] BW_R7, 
    input wire [6:0] BW_R8, 
    input wire [6:0] BW_R9,
    input wire [6:0] BW_R10, 
    input wire [6:0] BW_R11, 
    input wire [6:0] BW_R12, 
    input wire [6:0] BW_R13, 
    input wire [6:0] BW_R14, 
    input wire [6:0] BW_R15, 
    input wire [6:0] BW_R16, 
    input wire [6:0] BW_R17, 
    input wire [6:0] BW_R18,
    input wire [11:0] BW_Phi0, 
    input wire [11:0] BW_Phi1, 
    input wire [11:0] BW_Phi2, 
    input wire [11:0] BW_Phi3,

    input wire isAside,
    input wire [7:0] HotROIdef_SSC0,
    input wire [7:0] HotROIdef_SSC1,
    input wire [7:0] HotROIdef_SSC2,
    input wire [7:0] HotROIdef_SSC3,
    input wire [7:0] HotROIdef_SSC4,
    input wire [7:0] HotROIdef_SSC5,
    input wire [7:0] HotROIdef_SSC6,
    input wire [7:0] HotROIdef_SSC7,
    input wire [7:0] HotROIdef_SSC8,
    input wire [7:0] HotROIdef_SSC9,
    input wire [7:0] HotROIdef_SSC10,
    input wire [7:0] HotROIdef_SSC11,
    input wire [7:0] HotROIdef_SSC12,
    input wire [7:0] HotROIdef_SSC13,
    input wire [7:0] HotROIdef_SSC14,
    input wire [7:0] HotROIdef_SSC15,
    input wire [7:0] HotROIdef_SSC16,
    input wire [7:0] HotROIdef_SSC17,
    input wire [7:0] HotROIdef_SSC18,
   
    input wire [95:0] NSW_0_in,
    input wire [95:0] NSW_1_in,
    input wire [95:0] NSW_2_in,
    input wire [95:0] NSW_3_in,
    input wire [95:0] RPC_in,
    input wire [6:0] EI_0_in,
    input wire [6:0] EI_1_in,
    input wire [6:0] EI_2_in,
    input wire [11:0] Tile_in,

    input wire [7:0] Align_eta0_NSW_in,
    input wire [7:0] Align_eta1_NSW_in,
    input wire [7:0] Align_eta2_NSW_in,
    input wire [7:0] Align_eta3_NSW_in,
    input wire [5:0] Align_eta_RPC_in,
    input wire [5:0] Align_phi0_NSW_in,
    input wire [5:0] Align_phi1_NSW_in,
    input wire [5:0] Align_phi2_NSW_in,
    input wire [5:0] Align_phi3_NSW_in,
    input wire [5:0] Align_phi_RPC_in,

    input wire [5:0] Eta_sub_SSC0,
    input wire [5:0] Eta_sub_SSC1,
    input wire [5:0] Eta_sub_SSC2,
    input wire [5:0] Eta_sub_SSC3,
    input wire [5:0] Eta_sub_SSC4,
    input wire [7:0] Eta_sub_SSC5,
    input wire [7:0] Eta_sub_SSC6,
    input wire [7:0] Eta_sub_SSC7,
    input wire [7:0] Eta_sub_SSC8,
    input wire [7:0] Eta_sub_SSC9,
    input wire [7:0] Eta_sub_SSC10,
    input wire [7:0] Eta_sub_SSC11,
    input wire [7:0] Eta_sub_SSC12,
    input wire [7:0] Eta_sub_SSC13,
    input wire [7:0] Eta_sub_SSC14,
    input wire [7:0] Eta_sub_SSC15,
    input wire [7:0] Eta_sub_SSC16,
    input wire [7:0] Eta_sub_SSC17,
    input wire [7:0] Eta_sub_SSC18,
    input wire [5:0] Phi_sub0_NSW,
    input wire [5:0] Phi_sub1_NSW,
    input wire [5:0] Phi_sub2_NSW,
    input wire [5:0] Phi_sub3_NSW,
    input wire [5:0] Phi_sub0_RPC,
    input wire [5:0] Phi_sub1_RPC,
    input wire [5:0] Phi_sub2_RPC,
    input wire [5:0] Phi_sub3_RPC,

    input wire NSW0_data_error,
    input wire NSW1_data_error,
    input wire NSW2_data_error,
    input wire NSW3_data_error,
    input wire RPC_data_error,
    input wire EI_data_error,
    input wire Tile_data_error,

    input wire [13:0] NSWdisableSSC,
    input wire [4:0] EIdisableSSC,
    input wire [4:0] TILEdisableSSC,
    input wire [4:0] RPCdisableSSC,    
    
    input wire [6:0] EIMask_0_in_SSC0,
    input wire [6:0] EIMask_1_in_SSC0,
    input wire [6:0] EIMask_2_in_SSC0,
    input wire [6:0] EIMask_0_in_SSC1,
    input wire [6:0] EIMask_1_in_SSC1,
    input wire [6:0] EIMask_2_in_SSC1,
    input wire [6:0] EIMask_0_in_SSC2,
    input wire [6:0] EIMask_1_in_SSC2,
    input wire [6:0] EIMask_2_in_SSC2,
    input wire [6:0] EIMask_0_in_SSC3,
    input wire [6:0] EIMask_1_in_SSC3,
    input wire [6:0] EIMask_2_in_SSC3,
    input wire [6:0] EIMask_0_in_SSC4,
    input wire [6:0] EIMask_1_in_SSC4,
    input wire [6:0] EIMask_2_in_SSC4,
    input wire [1:0] TileMask0_SSC0,
    input wire [1:0] TileMask1_SSC0,
    input wire [1:0] TileMask2_SSC0,
    input wire [1:0] TileMask3_SSC0,
    input wire [1:0] TileMask0_SSC1,
    input wire [1:0] TileMask1_SSC1,
    input wire [1:0] TileMask2_SSC1,
    input wire [1:0] TileMask3_SSC1,
    input wire [1:0] TileMask0_SSC2,
    input wire [1:0] TileMask1_SSC2,
    input wire [1:0] TileMask2_SSC2,
    input wire [1:0] TileMask3_SSC2,
    input wire [1:0] TileMask0_SSC3,
    input wire [1:0] TileMask1_SSC3,
    input wire [1:0] TileMask2_SSC3,
    input wire [1:0] TileMask3_SSC3,
    input wire [1:0] TileMask0_SSC4,
    input wire [1:0] TileMask1_SSC4,
    input wire [1:0] TileMask2_SSC4,
    input wire [1:0] TileMask3_SSC4,
    
    output wire [9:0] trig_SSC0_BW,
    output wire [9:0] trig_SSC1_BW,
    output wire [9:0] trig_SSC2_BW,
    output wire [9:0] trig_SSC3_BW,
    output wire [9:0] trig_SSC4_BW,
    output wire [9:0] trig_SSC5_BW,
    output wire [9:0] trig_SSC6_BW,
    output wire [9:0] trig_SSC7_BW,
    output wire [9:0] trig_SSC8_BW,
    output wire [9:0] trig_SSC9_BW,
    output wire [9:0] trig_SSC10_BW,
    output wire [9:0] trig_SSC11_BW,
    output wire [9:0] trig_SSC12_BW,
    output wire [9:0] trig_SSC13_BW,
    output wire [9:0] trig_SSC14_BW,
    output wire [9:0] trig_SSC15_BW,
    output wire [9:0] trig_SSC16_BW,
    output wire [9:0] trig_SSC17_BW,
    output wire [9:0] trig_SSC18_BW,
    
    output wire [63:0] Inner_decoded_SSC0,
    output wire [63:0] Inner_decoded_SSC1,
    output wire [63:0] Inner_decoded_SSC2,
    output wire [63:0] Inner_decoded_SSC3,
    output wire [63:0] Inner_decoded_SSC4,
    output wire [239:0] Inner_decoded_SSC5,
    output wire [239:0] Inner_decoded_SSC6,
    output wire [239:0] Inner_decoded_SSC7,
    output wire [239:0] Inner_decoded_SSC8,
    output wire [239:0] Inner_decoded_SSC9,
    output wire [239:0] Inner_decoded_SSC10,
    output wire [239:0] Inner_decoded_SSC11,
    output wire [239:0] Inner_decoded_SSC12,
    output wire [239:0] Inner_decoded_SSC13,
    output wire [239:0] Inner_decoded_SSC14,
    output wire [239:0] Inner_decoded_SSC15,
    output wire [239:0] Inner_decoded_SSC16,
    output wire [239:0] Inner_decoded_SSC17,
    output wire [239:0] Inner_decoded_SSC18,
    
    output wire [14:0] trig_SSC0,
    output wire [14:0] trig_SSC1,
    output wire [14:0] trig_SSC2,
    output wire [14:0] trig_SSC3,
    output wire [14:0] trig_SSC4,
    output wire [14:0] trig_SSC5,
    output wire [14:0] trig_SSC6,
    output wire [14:0] trig_SSC7,
    output wire [14:0] trig_SSC8,
    output wire [14:0] trig_SSC9,
    output wire [14:0] trig_SSC10,
    output wire [14:0] trig_SSC11,
    output wire [14:0] trig_SSC12,
    output wire [14:0] trig_SSC13,
    output wire [14:0] trig_SSC14,
    output wire [14:0] trig_SSC15,
    output wire [14:0] trig_SSC16,
    output wire [14:0] trig_SSC17,
    output wire [14:0] trig_SSC18,
    
    output wire valid_SSC0,
    output wire valid_SSC1,
    output wire valid_SSC2,
    output wire valid_SSC3,
    output wire valid_SSC4,
    output wire valid_SSC5,
    output wire valid_SSC6,
    output wire valid_SSC7,
    output wire valid_SSC8,
    output wire valid_SSC9,
    output wire valid_SSC10,
    output wire valid_SSC11,
    output wire valid_SSC12,
    output wire valid_SSC13,
    output wire valid_SSC14,
    output wire valid_SSC15,
    output wire valid_SSC16,
    output wire valid_SSC17,
    output wire valid_SSC18
);
        
    
wire LUT_init_R0_in = (LUT_init_RoI_in[7:3] == 5'd0) ? 1'b1 : 1'b0;
wire LUT_init_R1_in = (LUT_init_RoI_in[7:3] == 5'd1) ? 1'b1 : 1'b0;
wire LUT_init_R2_in = (LUT_init_RoI_in[7:3] == 5'd2) ? 1'b1 : 1'b0;
wire LUT_init_R3_in = (LUT_init_RoI_in[7:3] == 5'd3) ? 1'b1 : 1'b0;
wire LUT_init_R4_in = (LUT_init_RoI_in[7:3] == 5'd4) ? 1'b1 : 1'b0;
wire LUT_init_R5_in = (LUT_init_RoI_in[7:3] == 5'd5) ? 1'b1 : 1'b0;
wire LUT_init_R6_in = (LUT_init_RoI_in[7:3] == 5'd6) ? 1'b1 : 1'b0;
wire LUT_init_R7_in = (LUT_init_RoI_in[7:3] == 5'd7) ? 1'b1 : 1'b0;
wire LUT_init_R8_in = (LUT_init_RoI_in[7:3] == 5'd8) ? 1'b1 : 1'b0;
wire LUT_init_R9_in = (LUT_init_RoI_in[7:3] == 5'd9) ? 1'b1 : 1'b0;
wire LUT_init_R10_in = (LUT_init_RoI_in[7:3] == 5'd10) ? 1'b1 : 1'b0;
wire LUT_init_R11_in = (LUT_init_RoI_in[7:3] == 5'd11) ? 1'b1 : 1'b0;
wire LUT_init_R12_in = (LUT_init_RoI_in[7:3] == 5'd12) ? 1'b1 : 1'b0;
wire LUT_init_R13_in = (LUT_init_RoI_in[7:3] == 5'd13) ? 1'b1 : 1'b0;
wire LUT_init_R14_in = (LUT_init_RoI_in[7:3] == 5'd14) ? 1'b1 : 1'b0;
wire LUT_init_R15_in = (LUT_init_RoI_in[7:3] == 5'd15) ? 1'b1 : 1'b0;
wire LUT_init_R16_in = (LUT_init_RoI_in[7:3] == 5'd16) ? 1'b1 : 1'b0;
wire LUT_init_R17_in = (LUT_init_RoI_in[7:3] == 5'd17) ? 1'b1 : 1'b0;
wire LUT_init_R18_in = (LUT_init_RoI_in[7:3] == 5'd18) ? 1'b1 : 1'b0;
wire [1:0] LUT_init_Phi_in = LUT_init_RoI_in[1:0];

wire LUT_rd_R0_in = (LUT_rd_RoI_in[7:3] == 5'd0) ? 1'b1 : 1'b0;
wire LUT_rd_R1_in = (LUT_rd_RoI_in[7:3] == 5'd1) ? 1'b1 : 1'b0;
wire LUT_rd_R2_in = (LUT_rd_RoI_in[7:3] == 5'd2) ? 1'b1 : 1'b0;
wire LUT_rd_R3_in = (LUT_rd_RoI_in[7:3] == 5'd3) ? 1'b1 : 1'b0;
wire LUT_rd_R4_in = (LUT_rd_RoI_in[7:3] == 5'd4) ? 1'b1 : 1'b0;
wire LUT_rd_R5_in = (LUT_rd_RoI_in[7:3] == 5'd5) ? 1'b1 : 1'b0;
wire LUT_rd_R6_in = (LUT_rd_RoI_in[7:3] == 5'd6) ? 1'b1 : 1'b0;
wire LUT_rd_R7_in = (LUT_rd_RoI_in[7:3] == 5'd7) ? 1'b1 : 1'b0;
wire LUT_rd_R8_in = (LUT_rd_RoI_in[7:3] == 5'd8) ? 1'b1 : 1'b0;
wire LUT_rd_R9_in = (LUT_rd_RoI_in[7:3] == 5'd9) ? 1'b1 : 1'b0;
wire LUT_rd_R10_in = (LUT_rd_RoI_in[7:3] == 5'd10) ? 1'b1 : 1'b0;
wire LUT_rd_R11_in = (LUT_rd_RoI_in[7:3] == 5'd11) ? 1'b1 : 1'b0;
wire LUT_rd_R12_in = (LUT_rd_RoI_in[7:3] == 5'd12) ? 1'b1 : 1'b0;
wire LUT_rd_R13_in = (LUT_rd_RoI_in[7:3] == 5'd13) ? 1'b1 : 1'b0;
wire LUT_rd_R14_in = (LUT_rd_RoI_in[7:3] == 5'd14) ? 1'b1 : 1'b0;
wire LUT_rd_R15_in = (LUT_rd_RoI_in[7:3] == 5'd15) ? 1'b1 : 1'b0;
wire LUT_rd_R16_in = (LUT_rd_RoI_in[7:3] == 5'd16) ? 1'b1 : 1'b0;
wire LUT_rd_R17_in = (LUT_rd_RoI_in[7:3] == 5'd17) ? 1'b1 : 1'b0;
wire LUT_rd_R18_in = (LUT_rd_RoI_in[7:3] == 5'd18) ? 1'b1 : 1'b0;
wire [1:0] LUT_rd_Phi_in = LUT_rd_RoI_in[1:0];

//wire wea = LUT_init_flg_in;
//wire ena = 1'b1;

wire [4:0] LUT_rd_data_out_0, LUT_rd_data_out_1, LUT_rd_data_out_2, LUT_rd_data_out_3, LUT_rd_data_out_4, LUT_rd_data_out_5,
           LUT_rd_data_out_6, LUT_rd_data_out_7, LUT_rd_data_out_8, LUT_rd_data_out_9, LUT_rd_data_out_10, LUT_rd_data_out_11,
           LUT_rd_data_out_12, LUT_rd_data_out_13, LUT_rd_data_out_14, LUT_rd_data_out_15, LUT_rd_data_out_16, LUT_rd_data_out_17,
           LUT_rd_data_out_18;

assign LUT_rd_data_out[4:0] = LUT_rd_data_out_0 | LUT_rd_data_out_1 | LUT_rd_data_out_2 | LUT_rd_data_out_3 | LUT_rd_data_out_4 | LUT_rd_data_out_5
                            | LUT_rd_data_out_6 | LUT_rd_data_out_7 | LUT_rd_data_out_8 | LUT_rd_data_out_9 | LUT_rd_data_out_10 | LUT_rd_data_out_11
                            | LUT_rd_data_out_12 | LUT_rd_data_out_13 | LUT_rd_data_out_14 | LUT_rd_data_out_15 | LUT_rd_data_out_16 | LUT_rd_data_out_17 | LUT_rd_data_out_18;


SSC_Transition SSC0(
    .CLK_in     (CLK_in),
    .CLK_Q40    (CLK_Q40),
    .CLK_160    (CLK_160),
    .reset_in   (reset_in),
    .BW_R       (BW_R0),
    .BW_Phi0    (BW_Phi0[11:6]),
    .BW_Phi1    (BW_Phi0[5:0]),
    .BW_Phi2    (6'b0),
    .BW_Phi3    (6'b0),
    .isAside    (isAside),
    .HotROIdef  (HotROIdef_SSC0),
    .RPC_in         (RPC_in),
    .Align_eta_in   (Align_eta_RPC_in),
    .Align_phi_in   (Align_phi_RPC_in),
    .Eta_sub        (Eta_sub_SSC0),
    .Phi_sub0       (Phi_sub0_RPC),
    .Phi_sub1       (Phi_sub1_RPC),
    .Phi_sub2       (Phi_sub2_RPC),
    .Phi_sub3       (Phi_sub3_RPC),
    .EI_0_in        (EI_0_in),
    .EI_1_in        (EI_1_in),
    .EI_2_in        (EI_2_in),
    .EIMask_0_in    (EIMask_0_in_SSC0),
    .EIMask_1_in    (EIMask_1_in_SSC0),
    .EIMask_2_in    (EIMask_2_in_SSC0),
    .Tile_in        (Tile_in),
    .TileMask0      (TileMask0_SSC0),
    .TileMask1      (TileMask1_SSC0),
    .TileMask2      (TileMask2_SSC0),
    .TileMask3      (TileMask3_SSC0),
    .EI_data_error  (EI_data_error),
    .Tile_data_error(Tile_data_error),
    .RPC_data_error (RPC_data_error),
    .EIdisable      (EIdisableSSC[0]), 
    .TILEdisable    (TILEdisableSSC[0]),    
    .RPCdisable     (RPCdisableSSC[0]),           
    .LUT_init_data_in     (LUT_init_data_in),
    .LUT_init_Address_in  (LUT_init_Address_in),
    .LUT_init_flg_in      (LUT_init_flag_in),
    .LUT_init_type_in     (LUT_init_type_in),
    .LUT_init_R_in        (LUT_init_R0_in),
    .LUT_init_Phi_in      (LUT_init_Phi_in),
    .LUT_init_mode_in     (LUT_init_mode_in),
    .LUT_rd_address_in    (LUT_rd_address_in),
    .LUT_rd_type_in       (LUT_rd_type_in),
    .LUT_rd_R_in          (LUT_rd_R0_in),
    .LUT_rd_Phi_in        (LUT_rd_Phi_in),
    .LUT_rd_data_out      (LUT_rd_data_out_0),
    .trig_SSC_BW    (trig_SSC0_BW),
    .trig_SSC       (trig_SSC0),
    .valid_SSC      (valid_SSC0),
    .Inner_decoded  (Inner_decoded_SSC0)
);
    
SSC_Transition SSC1(
    .CLK_in     (CLK_in),
    .CLK_Q40    (CLK_Q40),
    .CLK_160    (CLK_160),
    .reset_in   (reset_in),
    .BW_R       (BW_R1),
    .BW_Phi0    (BW_Phi0[11:6]),
    .BW_Phi1    (BW_Phi0[5:0]),
    .BW_Phi2    (6'b0),
    .BW_Phi3    (6'b0),
    .isAside    (isAside),
    .HotROIdef  (HotROIdef_SSC1),
    .RPC_in         (RPC_in),
    .Align_eta_in   (Align_eta_RPC_in),
    .Align_phi_in   (Align_phi_RPC_in),
    .Eta_sub        (Eta_sub_SSC1),
    .Phi_sub0       (Phi_sub0_RPC),
    .Phi_sub1       (Phi_sub1_RPC),
    .Phi_sub2       (Phi_sub2_RPC),
    .Phi_sub3       (Phi_sub3_RPC),
    .EI_0_in        (EI_0_in),
    .EI_1_in        (EI_1_in),
    .EI_2_in        (EI_2_in),
    .EIMask_0_in    (EIMask_0_in_SSC1),
    .EIMask_1_in    (EIMask_1_in_SSC1),
    .EIMask_2_in    (EIMask_2_in_SSC1),
    .Tile_in        (Tile_in),
    .TileMask0      (TileMask0_SSC1),
    .TileMask1      (TileMask1_SSC1),
    .TileMask2      (TileMask2_SSC1),
    .TileMask3      (TileMask3_SSC1),
    .EI_data_error  (EI_data_error),
    .Tile_data_error(Tile_data_error),
    .RPC_data_error (RPC_data_error),
    .EIdisable      (EIdisableSSC[1]), 
    .TILEdisable    (TILEdisableSSC[1]),    
    .RPCdisable     (RPCdisableSSC[1]),           
    .LUT_init_data_in     (LUT_init_data_in),
    .LUT_init_Address_in  (LUT_init_Address_in),
    .LUT_init_flg_in      (LUT_init_flag_in),
    .LUT_init_type_in     (LUT_init_type_in),
    .LUT_init_R_in        (LUT_init_R1_in),
    .LUT_init_Phi_in      (LUT_init_Phi_in),
    .LUT_init_mode_in     (LUT_init_mode_in),
    .LUT_rd_address_in    (LUT_rd_address_in),
    .LUT_rd_type_in       (LUT_rd_type_in),
    .LUT_rd_R_in          (LUT_rd_R1_in),
    .LUT_rd_Phi_in        (LUT_rd_Phi_in),
    .LUT_rd_data_out      (LUT_rd_data_out_1),
    .trig_SSC_BW    (trig_SSC1_BW),
    .trig_SSC       (trig_SSC1),
    .valid_SSC      (valid_SSC1),
    .Inner_decoded  (Inner_decoded_SSC1)
);
    
SSC_Transition SSC2(
    .CLK_in     (CLK_in),
    .CLK_Q40    (CLK_Q40),
    .CLK_160    (CLK_160),
    .reset_in   (reset_in),
    .BW_R       (BW_R2),
    .BW_Phi0    (BW_Phi1[11:6]),
    .BW_Phi1    (BW_Phi1[5:0]),
    .BW_Phi2    (BW_Phi0[11:6]),
    .BW_Phi3    (BW_Phi0[5:0]),
    .isAside    (isAside),
    .HotROIdef  (HotROIdef_SSC2),
    .RPC_in         (RPC_in),
    .Align_eta_in   (Align_eta_RPC_in),
    .Align_phi_in   (Align_phi_RPC_in),
    .Eta_sub        (Eta_sub_SSC2),
    .Phi_sub0       (Phi_sub0_RPC),
    .Phi_sub1       (Phi_sub1_RPC),
    .Phi_sub2       (Phi_sub2_RPC),
    .Phi_sub3       (Phi_sub3_RPC),
    .EI_0_in        (EI_0_in),
    .EI_1_in        (EI_1_in),
    .EI_2_in        (EI_2_in),
    .EIMask_0_in    (EIMask_0_in_SSC2),
    .EIMask_1_in    (EIMask_1_in_SSC2),
    .EIMask_2_in    (EIMask_2_in_SSC2),
    .Tile_in        (Tile_in),
    .TileMask0      (TileMask0_SSC2),
    .TileMask1      (TileMask1_SSC2),
    .TileMask2      (TileMask2_SSC2),
    .TileMask3      (TileMask3_SSC2),
    .EI_data_error  (EI_data_error),
    .Tile_data_error(Tile_data_error),
    .RPC_data_error (RPC_data_error),
    .EIdisable      (EIdisableSSC[2]), 
    .TILEdisable    (TILEdisableSSC[2]),    
    .RPCdisable     (RPCdisableSSC[2]),           
    .LUT_init_data_in     (LUT_init_data_in),
    .LUT_init_Address_in  (LUT_init_Address_in),
    .LUT_init_flg_in      (LUT_init_flag_in),
    .LUT_init_type_in     (LUT_init_type_in),
    .LUT_init_R_in        (LUT_init_R2_in),
    .LUT_init_Phi_in      (LUT_init_Phi_in),
    .LUT_init_mode_in     (LUT_init_mode_in),
    .LUT_rd_address_in    (LUT_rd_address_in),
    .LUT_rd_type_in       (LUT_rd_type_in),
    .LUT_rd_R_in          (LUT_rd_R2_in),
    .LUT_rd_Phi_in        (LUT_rd_Phi_in),
    .LUT_rd_data_out      (LUT_rd_data_out_2),
    .trig_SSC_BW    (trig_SSC2_BW),
    .trig_SSC       (trig_SSC2),
    .valid_SSC      (valid_SSC2),
    .Inner_decoded  (Inner_decoded_SSC2)
);
    
SSC_Transition SSC3(
    .CLK_in     (CLK_in),
    .CLK_Q40    (CLK_Q40),
    .CLK_160    (CLK_160),
    .reset_in   (reset_in),
    .BW_R       (BW_R3),
    .BW_Phi0    (BW_Phi1[11:6]),
    .BW_Phi1    (BW_Phi1[5:0]),
    .BW_Phi2    (6'b0),
    .BW_Phi3    (6'b0),
    .isAside    (isAside),
    .HotROIdef  (HotROIdef_SSC3),
    .RPC_in         (RPC_in),
    .Align_eta_in   (Align_eta_RPC_in),
    .Align_phi_in   (Align_phi_RPC_in),
    .Eta_sub        (Eta_sub_SSC3),
    .Phi_sub0       (Phi_sub0_RPC),
    .Phi_sub1       (Phi_sub1_RPC),
    .Phi_sub2       (Phi_sub2_RPC),
    .Phi_sub3       (Phi_sub3_RPC),
    .EI_0_in        (EI_0_in),
    .EI_1_in        (EI_1_in),
    .EI_2_in        (EI_2_in),
    .EIMask_0_in    (EIMask_0_in_SSC3),
    .EIMask_1_in    (EIMask_1_in_SSC3),
    .EIMask_2_in    (EIMask_2_in_SSC3),
    .Tile_in        (Tile_in),
    .TileMask0      (TileMask0_SSC3),
    .TileMask1      (TileMask1_SSC3),
    .TileMask2      (TileMask2_SSC3),
    .TileMask3      (TileMask3_SSC3),
    .EI_data_error  (EI_data_error),
    .Tile_data_error(Tile_data_error),
    .RPC_data_error (RPC_data_error),
    .EIdisable      (EIdisableSSC[3]), 
    .TILEdisable    (TILEdisableSSC[3]),    
    .RPCdisable     (RPCdisableSSC[3]),           
    .LUT_init_data_in     (LUT_init_data_in),
    .LUT_init_Address_in  (LUT_init_Address_in),
    .LUT_init_flg_in      (LUT_init_flag_in),
    .LUT_init_type_in     (LUT_init_type_in),
    .LUT_init_R_in        (LUT_init_R3_in),
    .LUT_init_Phi_in      (LUT_init_Phi_in),
    .LUT_init_mode_in     (LUT_init_mode_in),
    .LUT_rd_address_in    (LUT_rd_address_in),
    .LUT_rd_type_in       (LUT_rd_type_in),
    .LUT_rd_R_in          (LUT_rd_R3_in),
    .LUT_rd_Phi_in        (LUT_rd_Phi_in),
    .LUT_rd_data_out      (LUT_rd_data_out_3),
    .trig_SSC_BW    (trig_SSC3_BW),
    .trig_SSC       (trig_SSC3),
    .valid_SSC      (valid_SSC3),
    .Inner_decoded  (Inner_decoded_SSC3)
);
    
SSC_Transition SSC4(
    .CLK_in     (CLK_in),
    .CLK_Q40    (CLK_Q40),
    .CLK_160    (CLK_160),
    .reset_in   (reset_in),
    .BW_R       (BW_R4),
    .BW_Phi0    (BW_Phi2[11:6]),
    .BW_Phi1    (BW_Phi2[5:0]),
    .BW_Phi2    (BW_Phi1[11:6]),
    .BW_Phi3    (BW_Phi1[5:0]),
    .isAside    (isAside),
    .HotROIdef  (HotROIdef_SSC4),
    .RPC_in         (RPC_in),
    .Align_eta_in   (Align_eta_RPC_in),
    .Align_phi_in   (Align_phi_RPC_in),
    .Eta_sub        (Eta_sub_SSC4),
    .Phi_sub0       (Phi_sub0_RPC),
    .Phi_sub1       (Phi_sub1_RPC),
    .Phi_sub2       (Phi_sub2_RPC),
    .Phi_sub3       (Phi_sub3_RPC),
    .EI_0_in        (EI_0_in),
    .EI_1_in        (EI_1_in),
    .EI_2_in        (EI_2_in),
    .EIMask_0_in    (EIMask_0_in_SSC4),
    .EIMask_1_in    (EIMask_1_in_SSC4),
    .EIMask_2_in    (EIMask_2_in_SSC4),
    .Tile_in        (Tile_in),
    .TileMask0      (TileMask0_SSC4),
    .TileMask1      (TileMask1_SSC4),
    .TileMask2      (TileMask2_SSC4),
    .TileMask3      (TileMask3_SSC4),
    .EI_data_error  (EI_data_error),
    .Tile_data_error(Tile_data_error),
    .RPC_data_error (RPC_data_error),
    .EIdisable      (EIdisableSSC[4]), 
    .TILEdisable    (TILEdisableSSC[4]),    
    .RPCdisable     (RPCdisableSSC[4]),           
    .LUT_init_data_in     (LUT_init_data_in),
    .LUT_init_Address_in  (LUT_init_Address_in),
    .LUT_init_flg_in      (LUT_init_flag_in),
    .LUT_init_type_in     (LUT_init_type_in),
    .LUT_init_R_in        (LUT_init_R4_in),
    .LUT_init_Phi_in      (LUT_init_Phi_in),
    .LUT_init_mode_in     (LUT_init_mode_in),
    .LUT_rd_address_in    (LUT_rd_address_in),
    .LUT_rd_type_in       (LUT_rd_type_in),
    .LUT_rd_R_in          (LUT_rd_R4_in),
    .LUT_rd_Phi_in        (LUT_rd_Phi_in),
    .LUT_rd_data_out      (LUT_rd_data_out_4),
    .trig_SSC_BW    (trig_SSC4_BW),
    .trig_SSC       (trig_SSC4),
    .valid_SSC      (valid_SSC4),
    .Inner_decoded  (Inner_decoded_SSC4)
);
    
SSC SSC5(
    .CLK_in     (CLK_in),
    .CLK_Q40    (CLK_Q40),
    .CLK_320    (CLK_320),
    .reset_in   (reset_in),
    .BW_R       (BW_R5),
    .BW_Phi0    (BW_Phi2[11:6]),
    .BW_Phi1    (BW_Phi2[5:0]),
    .BW_Phi2    (6'b0),
    .BW_Phi3    (6'b0),
    .isAside    (isAside),
    .HotROIdef  (HotROIdef_SSC5),
    .NSW_0_in         (NSW_0_in),
    .NSW_1_in         (NSW_1_in),
    .NSW_2_in         (NSW_2_in),
    .NSW_3_in         (NSW_3_in),
    .Align_eta0_in    (Align_eta0_NSW_in),
    .Align_eta1_in    (Align_eta1_NSW_in),
    .Align_eta2_in    (Align_eta2_NSW_in),
    .Align_eta3_in    (Align_eta3_NSW_in),
    .Align_phi0_in    (Align_phi0_NSW_in),
    .Align_phi1_in    (Align_phi1_NSW_in),
    .Align_phi2_in    (Align_phi2_NSW_in),
    .Align_phi3_in    (Align_phi3_NSW_in),
    .Eta_sub          (Eta_sub_SSC5),
    .Phi_sub0         (Phi_sub0_NSW),
    .Phi_sub1         (Phi_sub1_NSW),
    .Phi_sub2         (Phi_sub2_NSW),
    .Phi_sub3         (Phi_sub3_NSW),
    .NSW0_data_error  (NSW0_data_error),
    .NSW1_data_error  (NSW1_data_error),
    .NSW2_data_error  (NSW2_data_error),
    .NSW3_data_error  (NSW3_data_error),
    .NSWdisable       (NSWdisableSSC[0]),
    .LUT_init_data_in     (LUT_init_data_in),
    .LUT_init_Address_in  (LUT_init_Address_in[13:0]),
    .LUT_init_flg_in      (LUT_init_flag_in),
    .LUT_init_type_in     (LUT_init_type_in),
    .LUT_init_R_in        (LUT_init_R5_in),
    .LUT_init_Phi_in      (LUT_init_Phi_in),
    .LUT_init_mode_in     (LUT_init_mode_in),
    .LUT_rd_address_in    (LUT_rd_address_in[13:0]),
    .LUT_rd_type_in       (LUT_rd_type_in),
    .LUT_rd_R_in          (LUT_rd_R5_in),
    .LUT_rd_Phi_in        (LUT_rd_Phi_in),
    .LUT_rd_data_out      (LUT_rd_data_out_5),
    .trig_SSC_BW      (trig_SSC5_BW),
    .trig_SSC         (trig_SSC5),
    .valid_SSC        (valid_SSC5),
    .Inner_decoded    (Inner_decoded_SSC5)
);
    
SSC6 SSC6(
    .CLK_in     (CLK_in),
    .CLK_Q40    (CLK_Q40),
    .CLK_320    (CLK_320),
    .reset_in   (reset_in),
    .BW_R       (BW_R6),
    .BW_Phi0    (BW_Phi3[11:6]),
    .BW_Phi1    (BW_Phi3[5:0]),
    .BW_Phi2    (BW_Phi2[11:6]),
    .BW_Phi3    (BW_Phi2[5:0]),
    .isAside    (isAside),
    .HotROIdef  (HotROIdef_SSC6),
    .NSW_0_in         (NSW_0_in),
    .NSW_1_in         (NSW_1_in),
    .NSW_2_in         (NSW_2_in),
    .NSW_3_in         (NSW_3_in),
    .Align_eta0_in    (Align_eta0_NSW_in),
    .Align_eta1_in    (Align_eta1_NSW_in),
    .Align_eta2_in    (Align_eta2_NSW_in),
    .Align_eta3_in    (Align_eta3_NSW_in),
    .Align_phi0_in    (Align_phi0_NSW_in),
    .Align_phi1_in    (Align_phi1_NSW_in),
    .Align_phi2_in    (Align_phi2_NSW_in),
    .Align_phi3_in    (Align_phi3_NSW_in),
    .Eta_sub          (Eta_sub_SSC6),
    .Phi_sub0         (Phi_sub0_NSW),
    .Phi_sub1         (Phi_sub1_NSW),
    .Phi_sub2         (Phi_sub2_NSW),
    .Phi_sub3         (Phi_sub3_NSW),
    .NSW0_data_error  (NSW0_data_error),
    .NSW1_data_error  (NSW1_data_error),
    .NSW2_data_error  (NSW2_data_error),
    .NSW3_data_error  (NSW3_data_error),
    .NSWdisable       (NSWdisableSSC[1]),
    .LUT_init_data_in     (LUT_init_data_in),
    .LUT_init_Address_in  (LUT_init_Address_in[13:0]),
    .LUT_init_flg_in      (LUT_init_flag_in),
    .LUT_init_type_in     (LUT_init_type_in),
    .LUT_init_R_in        (LUT_init_R6_in),
    .LUT_init_Phi_in      (LUT_init_Phi_in),
    .LUT_init_mode_in     (LUT_init_mode_in),
    .LUT_rd_address_in    (LUT_rd_address_in[13:0]),
    .LUT_rd_type_in       (LUT_rd_type_in),
    .LUT_rd_R_in          (LUT_rd_R6_in),
    .LUT_rd_Phi_in        (LUT_rd_Phi_in),
    .LUT_rd_data_out      (LUT_rd_data_out_6),
    .trig_SSC_BW      (trig_SSC6_BW),
    .trig_SSC         (trig_SSC6),
    .valid_SSC        (valid_SSC6),
    .Inner_decoded    (Inner_decoded_SSC6)
);
    
SSC SSC7(
    .CLK_in     (CLK_in),
    .CLK_Q40    (CLK_Q40),
    .CLK_320    (CLK_320),
    .reset_in   (reset_in),
    .BW_R       (BW_R7),
    .BW_Phi0    (BW_Phi3[11:6]),
    .BW_Phi1    (BW_Phi3[5:0]),
    .BW_Phi2    (6'b0),
    .BW_Phi3    (6'b0),
    .isAside    (isAside),
    .HotROIdef  (HotROIdef_SSC7),
    .NSW_0_in         (NSW_0_in),
    .NSW_1_in         (NSW_1_in),
    .NSW_2_in         (NSW_2_in),
    .NSW_3_in         (NSW_3_in),
    .Align_eta0_in    (Align_eta0_NSW_in),
    .Align_eta1_in    (Align_eta1_NSW_in),
    .Align_eta2_in    (Align_eta2_NSW_in),
    .Align_eta3_in    (Align_eta3_NSW_in),
    .Align_phi0_in    (Align_phi0_NSW_in),
    .Align_phi1_in    (Align_phi1_NSW_in),
    .Align_phi2_in    (Align_phi2_NSW_in),
    .Align_phi3_in    (Align_phi3_NSW_in),
    .Eta_sub          (Eta_sub_SSC7),
    .Phi_sub0         (Phi_sub0_NSW),
    .Phi_sub1         (Phi_sub1_NSW),
    .Phi_sub2         (Phi_sub2_NSW),
    .Phi_sub3         (Phi_sub3_NSW),
    .NSW0_data_error  (NSW0_data_error),
    .NSW1_data_error  (NSW1_data_error),
    .NSW2_data_error  (NSW2_data_error),
    .NSW3_data_error  (NSW3_data_error),
    .NSWdisable       (NSWdisableSSC[2]),
    .LUT_init_data_in     (LUT_init_data_in),
    .LUT_init_Address_in  (LUT_init_Address_in[13:0]),
    .LUT_init_flg_in      (LUT_init_flag_in),
    .LUT_init_type_in     (LUT_init_type_in),
    .LUT_init_R_in        (LUT_init_R7_in),
    .LUT_init_Phi_in      (LUT_init_Phi_in),
    .LUT_init_mode_in     (LUT_init_mode_in),
    .LUT_rd_address_in    (LUT_rd_address_in[13:0]),
    .LUT_rd_type_in       (LUT_rd_type_in),
    .LUT_rd_R_in          (LUT_rd_R7_in),
    .LUT_rd_Phi_in        (LUT_rd_Phi_in),
    .LUT_rd_data_out      (LUT_rd_data_out_7),
    .trig_SSC_BW      (trig_SSC7_BW),
    .trig_SSC         (trig_SSC7),
    .valid_SSC        (valid_SSC7),
    .Inner_decoded    (Inner_decoded_SSC7)
);
    
SSC SSC8(
    .CLK_in     (CLK_in),
    .CLK_Q40    (CLK_Q40),
    .CLK_320    (CLK_320),
    .reset_in   (reset_in),
    .BW_R       (BW_R8),
    .BW_Phi0    (BW_Phi3[11:6]),
    .BW_Phi1    (BW_Phi3[5:0]),
    .BW_Phi2    (6'b0),
    .BW_Phi3    (6'b0),
    .isAside    (isAside),
    .HotROIdef  (HotROIdef_SSC8),
    .NSW_0_in         (NSW_0_in),
    .NSW_1_in         (NSW_1_in),
    .NSW_2_in         (NSW_2_in),
    .NSW_3_in         (NSW_3_in),
    .Align_eta0_in    (Align_eta0_NSW_in),
    .Align_eta1_in    (Align_eta1_NSW_in),
    .Align_eta2_in    (Align_eta2_NSW_in),
    .Align_eta3_in    (Align_eta3_NSW_in),
    .Align_phi0_in    (Align_phi0_NSW_in),
    .Align_phi1_in    (Align_phi1_NSW_in),
    .Align_phi2_in    (Align_phi2_NSW_in),
    .Align_phi3_in    (Align_phi3_NSW_in),
    .Eta_sub          (Eta_sub_SSC8),
    .Phi_sub0         (Phi_sub0_NSW),
    .Phi_sub1         (Phi_sub1_NSW),
    .Phi_sub2         (Phi_sub2_NSW),
    .Phi_sub3         (Phi_sub3_NSW),
    .NSW0_data_error  (NSW0_data_error),
    .NSW1_data_error  (NSW1_data_error),
    .NSW2_data_error  (NSW2_data_error),
    .NSW3_data_error  (NSW3_data_error),
    .NSWdisable       (NSWdisableSSC[3]),
    .LUT_init_data_in     (LUT_init_data_in),
    .LUT_init_Address_in  (LUT_init_Address_in[13:0]),
    .LUT_init_flg_in      (LUT_init_flag_in),
    .LUT_init_type_in     (LUT_init_type_in),
    .LUT_init_R_in        (LUT_init_R8_in),
    .LUT_init_Phi_in      (LUT_init_Phi_in),
    .LUT_init_mode_in     (LUT_init_mode_in),
    .LUT_rd_address_in    (LUT_rd_address_in[13:0]),
    .LUT_rd_type_in       (LUT_rd_type_in),
    .LUT_rd_R_in          (LUT_rd_R8_in),
    .LUT_rd_Phi_in        (LUT_rd_Phi_in),
    .LUT_rd_data_out      (LUT_rd_data_out_8),
    .trig_SSC_BW      (trig_SSC8_BW),
    .trig_SSC         (trig_SSC8),
    .valid_SSC        (valid_SSC8),
    .Inner_decoded    (Inner_decoded_SSC8)
);
    
SSC SSC9(
    .CLK_in     (CLK_in),
    .CLK_Q40    (CLK_Q40),
    .CLK_320    (CLK_320),
    .reset_in   (reset_in),
    .BW_R       (BW_R9),
    .BW_Phi0    (BW_Phi3[11:6]),
    .BW_Phi1    (BW_Phi3[5:0]),
    .BW_Phi2    (6'b0),
    .BW_Phi3    (6'b0),
    .isAside    (isAside),
    .HotROIdef  (HotROIdef_SSC9),
    .NSW_0_in         (NSW_0_in),
    .NSW_1_in         (NSW_1_in),
    .NSW_2_in         (NSW_2_in),
    .NSW_3_in         (NSW_3_in),
    .Align_eta0_in    (Align_eta0_NSW_in),
    .Align_eta1_in    (Align_eta1_NSW_in),
    .Align_eta2_in    (Align_eta2_NSW_in),
    .Align_eta3_in    (Align_eta3_NSW_in),
    .Align_phi0_in    (Align_phi0_NSW_in),
    .Align_phi1_in    (Align_phi1_NSW_in),
    .Align_phi2_in    (Align_phi2_NSW_in),
    .Align_phi3_in    (Align_phi3_NSW_in),
    .Eta_sub          (Eta_sub_SSC9),
    .Phi_sub0         (Phi_sub0_NSW),
    .Phi_sub1         (Phi_sub1_NSW),
    .Phi_sub2         (Phi_sub2_NSW),
    .Phi_sub3         (Phi_sub3_NSW),
    .NSW0_data_error  (NSW0_data_error),
    .NSW1_data_error  (NSW1_data_error),
    .NSW2_data_error  (NSW2_data_error),
    .NSW3_data_error  (NSW3_data_error),
    .NSWdisable       (NSWdisableSSC[4]),
    .LUT_init_data_in     (LUT_init_data_in),
    .LUT_init_Address_in  (LUT_init_Address_in[13:0]),
    .LUT_init_flg_in      (LUT_init_flag_in),
    .LUT_init_type_in     (LUT_init_type_in),
    .LUT_init_R_in        (LUT_init_R9_in),
    .LUT_init_Phi_in      (LUT_init_Phi_in),
    .LUT_init_mode_in     (LUT_init_mode_in),
    .LUT_rd_address_in    (LUT_rd_address_in[13:0]),
    .LUT_rd_type_in       (LUT_rd_type_in),
    .LUT_rd_R_in          (LUT_rd_R9_in),
    .LUT_rd_Phi_in        (LUT_rd_Phi_in),
    .LUT_rd_data_out      (LUT_rd_data_out_9),
    .trig_SSC_BW      (trig_SSC9_BW),
    .trig_SSC         (trig_SSC9),
    .valid_SSC        (valid_SSC9),
    .Inner_decoded    (Inner_decoded_SSC9)
);
    
SSC SSC10(
    .CLK_in     (CLK_in),
    .CLK_Q40    (CLK_Q40),
    .CLK_320    (CLK_320),
    .reset_in   (reset_in),
    .BW_R       (BW_R10),
    .BW_Phi0    (BW_Phi3[11:6]),
    .BW_Phi1    (BW_Phi3[5:0]),
    .BW_Phi2    (6'b0),
    .BW_Phi3    (6'b0),
    .isAside    (isAside),
    .HotROIdef  (HotROIdef_SSC10),
    .NSW_0_in         (NSW_0_in),
    .NSW_1_in         (NSW_1_in),
    .NSW_2_in         (NSW_2_in),
    .NSW_3_in         (NSW_3_in),
    .Align_eta0_in    (Align_eta0_NSW_in),
    .Align_eta1_in    (Align_eta1_NSW_in),
    .Align_eta2_in    (Align_eta2_NSW_in),
    .Align_eta3_in    (Align_eta3_NSW_in),
    .Align_phi0_in    (Align_phi0_NSW_in),
    .Align_phi1_in    (Align_phi1_NSW_in),
    .Align_phi2_in    (Align_phi2_NSW_in),
    .Align_phi3_in    (Align_phi3_NSW_in),
    .Eta_sub          (Eta_sub_SSC10),
    .Phi_sub0         (Phi_sub0_NSW),
    .Phi_sub1         (Phi_sub1_NSW),
    .Phi_sub2         (Phi_sub2_NSW),
    .Phi_sub3         (Phi_sub3_NSW),
    .NSW0_data_error  (NSW0_data_error),
    .NSW1_data_error  (NSW1_data_error),
    .NSW2_data_error  (NSW2_data_error),
    .NSW3_data_error  (NSW3_data_error),
    .NSWdisable       (NSWdisableSSC[5]),
    .LUT_init_data_in     (LUT_init_data_in),
    .LUT_init_Address_in  (LUT_init_Address_in[13:0]),
    .LUT_init_flg_in      (LUT_init_flag_in),
    .LUT_init_type_in     (LUT_init_type_in),
    .LUT_init_R_in        (LUT_init_R10_in),
    .LUT_init_Phi_in      (LUT_init_Phi_in),
    .LUT_init_mode_in     (LUT_init_mode_in),
    .LUT_rd_address_in    (LUT_rd_address_in[13:0]),
    .LUT_rd_type_in       (LUT_rd_type_in),
    .LUT_rd_R_in          (LUT_rd_R10_in),
    .LUT_rd_Phi_in        (LUT_rd_Phi_in),
    .LUT_rd_data_out      (LUT_rd_data_out_10),
    .trig_SSC_BW      (trig_SSC10_BW),
    .trig_SSC         (trig_SSC10),
    .valid_SSC        (valid_SSC10),
    .Inner_decoded    (Inner_decoded_SSC10)
);
    
SSC SSC11(
    .CLK_in     (CLK_in),
    .CLK_Q40    (CLK_Q40),
    .CLK_320    (CLK_320),
    .reset_in   (reset_in),
    .BW_R       (BW_R11),
    .BW_Phi0    (BW_Phi3[11:6]),
    .BW_Phi1    (BW_Phi3[5:0]),
    .BW_Phi2    (6'b0),
    .BW_Phi3    (6'b0),
    .isAside    (isAside),
    .HotROIdef  (HotROIdef_SSC11),
    .NSW_0_in         (NSW_0_in),
    .NSW_1_in         (NSW_1_in),
    .NSW_2_in         (NSW_2_in),
    .NSW_3_in         (NSW_3_in),
    .Align_eta0_in    (Align_eta0_NSW_in),
    .Align_eta1_in    (Align_eta1_NSW_in),
    .Align_eta2_in    (Align_eta2_NSW_in),
    .Align_eta3_in    (Align_eta3_NSW_in),
    .Align_phi0_in    (Align_phi0_NSW_in),
    .Align_phi1_in    (Align_phi1_NSW_in),
    .Align_phi2_in    (Align_phi2_NSW_in),
    .Align_phi3_in    (Align_phi3_NSW_in),
    .Eta_sub          (Eta_sub_SSC11),
    .Phi_sub0         (Phi_sub0_NSW),
    .Phi_sub1         (Phi_sub1_NSW),
    .Phi_sub2         (Phi_sub2_NSW),
    .Phi_sub3         (Phi_sub3_NSW),
    .NSW0_data_error  (NSW0_data_error),
    .NSW1_data_error  (NSW1_data_error),
    .NSW2_data_error  (NSW2_data_error),
    .NSW3_data_error  (NSW3_data_error),
    .NSWdisable       (NSWdisableSSC[6]),
    .LUT_init_data_in     (LUT_init_data_in),
    .LUT_init_Address_in  (LUT_init_Address_in[13:0]),
    .LUT_init_flg_in      (LUT_init_flag_in),
    .LUT_init_type_in     (LUT_init_type_in),
    .LUT_init_R_in        (LUT_init_R11_in),
    .LUT_init_Phi_in      (LUT_init_Phi_in),
    .LUT_init_mode_in     (LUT_init_mode_in),
    .LUT_rd_address_in    (LUT_rd_address_in[13:0]),
    .LUT_rd_type_in       (LUT_rd_type_in),
    .LUT_rd_R_in          (LUT_rd_R11_in),
    .LUT_rd_Phi_in        (LUT_rd_Phi_in),
    .LUT_rd_data_out      (LUT_rd_data_out_11),
    .trig_SSC_BW      (trig_SSC11_BW),
    .trig_SSC         (trig_SSC11),
    .valid_SSC        (valid_SSC11),
    .Inner_decoded    (Inner_decoded_SSC11)
);
    
SSC SSC12(
    .CLK_in     (CLK_in),
    .CLK_Q40    (CLK_Q40),
    .CLK_320    (CLK_320),
    .reset_in   (reset_in),
    .BW_R       (BW_R12),
    .BW_Phi0    (BW_Phi3[11:6]),
    .BW_Phi1    (BW_Phi3[5:0]),
    .BW_Phi2    (6'b0),
    .BW_Phi3    (6'b0),
    .isAside    (isAside),
    .HotROIdef  (HotROIdef_SSC12),
    .NSW_0_in         (NSW_0_in),
    .NSW_1_in         (NSW_1_in),
    .NSW_2_in         (NSW_2_in),
    .NSW_3_in         (NSW_3_in),
    .Align_eta0_in    (Align_eta0_NSW_in),
    .Align_eta1_in    (Align_eta1_NSW_in),
    .Align_eta2_in    (Align_eta2_NSW_in),
    .Align_eta3_in    (Align_eta3_NSW_in),
    .Align_phi0_in    (Align_phi0_NSW_in),
    .Align_phi1_in    (Align_phi1_NSW_in),
    .Align_phi2_in    (Align_phi2_NSW_in),
    .Align_phi3_in    (Align_phi3_NSW_in),
    .Eta_sub          (Eta_sub_SSC12),
    .Phi_sub0         (Phi_sub0_NSW),
    .Phi_sub1         (Phi_sub1_NSW),
    .Phi_sub2         (Phi_sub2_NSW),
    .Phi_sub3         (Phi_sub3_NSW),
    .NSW0_data_error  (NSW0_data_error),
    .NSW1_data_error  (NSW1_data_error),
    .NSW2_data_error  (NSW2_data_error),
    .NSW3_data_error  (NSW3_data_error),
    .NSWdisable       (NSWdisableSSC[7]),
    .LUT_init_data_in     (LUT_init_data_in),
    .LUT_init_Address_in  (LUT_init_Address_in[13:0]),
    .LUT_init_flg_in      (LUT_init_flag_in),
    .LUT_init_type_in     (LUT_init_type_in),
    .LUT_init_R_in        (LUT_init_R12_in),
    .LUT_init_Phi_in      (LUT_init_Phi_in),
    .LUT_init_mode_in     (LUT_init_mode_in),
    .LUT_rd_address_in    (LUT_rd_address_in[13:0]),
    .LUT_rd_type_in       (LUT_rd_type_in),
    .LUT_rd_R_in          (LUT_rd_R12_in),
    .LUT_rd_Phi_in        (LUT_rd_Phi_in),
    .LUT_rd_data_out      (LUT_rd_data_out_12),
    .trig_SSC_BW      (trig_SSC12_BW),
    .trig_SSC         (trig_SSC12),
    .valid_SSC        (valid_SSC12),
    .Inner_decoded    (Inner_decoded_SSC12)
);
    
SSC SSC13(
    .CLK_in     (CLK_in),
    .CLK_Q40    (CLK_Q40),
    .CLK_320    (CLK_320),
    .reset_in   (reset_in),
    .BW_R       (BW_R13),
    .BW_Phi0    (BW_Phi3[11:6]),
    .BW_Phi1    (BW_Phi3[5:0]),
    .BW_Phi2    (6'b0),
    .BW_Phi3    (6'b0),
    .isAside    (isAside),
    .HotROIdef  (HotROIdef_SSC13),
    .NSW_0_in         (NSW_0_in),
    .NSW_1_in         (NSW_1_in),
    .NSW_2_in         (NSW_2_in),
    .NSW_3_in         (NSW_3_in),
    .Align_eta0_in    (Align_eta0_NSW_in),
    .Align_eta1_in    (Align_eta1_NSW_in),
    .Align_eta2_in    (Align_eta2_NSW_in),
    .Align_eta3_in    (Align_eta3_NSW_in),
    .Align_phi0_in    (Align_phi0_NSW_in),
    .Align_phi1_in    (Align_phi1_NSW_in),
    .Align_phi2_in    (Align_phi2_NSW_in),
    .Align_phi3_in    (Align_phi3_NSW_in),
    .Eta_sub          (Eta_sub_SSC13),
    .Phi_sub0         (Phi_sub0_NSW),
    .Phi_sub1         (Phi_sub1_NSW),
    .Phi_sub2         (Phi_sub2_NSW),
    .Phi_sub3         (Phi_sub3_NSW),
    .NSW0_data_error  (NSW0_data_error),
    .NSW1_data_error  (NSW1_data_error),
    .NSW2_data_error  (NSW2_data_error),
    .NSW3_data_error  (NSW3_data_error),
    .NSWdisable       (NSWdisableSSC[8]),
    .LUT_init_data_in     (LUT_init_data_in),
    .LUT_init_Address_in  (LUT_init_Address_in[13:0]),
    .LUT_init_flg_in      (LUT_init_flag_in),
    .LUT_init_type_in     (LUT_init_type_in),
    .LUT_init_R_in        (LUT_init_R13_in),
    .LUT_init_Phi_in      (LUT_init_Phi_in),
    .LUT_init_mode_in     (LUT_init_mode_in),
    .LUT_rd_address_in    (LUT_rd_address_in[13:0]),
    .LUT_rd_type_in       (LUT_rd_type_in),
    .LUT_rd_R_in          (LUT_rd_R13_in),
    .LUT_rd_Phi_in        (LUT_rd_Phi_in),
    .LUT_rd_data_out      (LUT_rd_data_out_13),
    .trig_SSC_BW      (trig_SSC13_BW),
    .trig_SSC         (trig_SSC13),
    .valid_SSC        (valid_SSC13),
    .Inner_decoded    (Inner_decoded_SSC13)
);
    
SSC SSC14(
    .CLK_in     (CLK_in),
    .CLK_Q40    (CLK_Q40),
    .CLK_320    (CLK_320),
    .reset_in   (reset_in),
    .BW_R       (BW_R14),
    .BW_Phi0    (BW_Phi3[11:6]),
    .BW_Phi1    (BW_Phi3[5:0]),
    .BW_Phi2    (6'b0),
    .BW_Phi3    (6'b0),
    .isAside    (isAside),
    .HotROIdef  (HotROIdef_SSC14),
    .NSW_0_in         (NSW_0_in),
    .NSW_1_in         (NSW_1_in),
    .NSW_2_in         (NSW_2_in),
    .NSW_3_in         (NSW_3_in),
    .Align_eta0_in    (Align_eta0_NSW_in),
    .Align_eta1_in    (Align_eta1_NSW_in),
    .Align_eta2_in    (Align_eta2_NSW_in),
    .Align_eta3_in    (Align_eta3_NSW_in),
    .Align_phi0_in    (Align_phi0_NSW_in),
    .Align_phi1_in    (Align_phi1_NSW_in),
    .Align_phi2_in    (Align_phi2_NSW_in),
    .Align_phi3_in    (Align_phi3_NSW_in),
    .Eta_sub          (Eta_sub_SSC14),
    .Phi_sub0         (Phi_sub0_NSW),
    .Phi_sub1         (Phi_sub1_NSW),
    .Phi_sub2         (Phi_sub2_NSW),
    .Phi_sub3         (Phi_sub3_NSW),
    .NSW0_data_error  (NSW0_data_error),
    .NSW1_data_error  (NSW1_data_error),
    .NSW2_data_error  (NSW2_data_error),
    .NSW3_data_error  (NSW3_data_error),
    .NSWdisable       (NSWdisableSSC[9]),
    .LUT_init_data_in     (LUT_init_data_in),
    .LUT_init_Address_in  (LUT_init_Address_in[13:0]),
    .LUT_init_flg_in      (LUT_init_flag_in),
    .LUT_init_type_in     (LUT_init_type_in),
    .LUT_init_R_in        (LUT_init_R14_in),
    .LUT_init_Phi_in      (LUT_init_Phi_in),
    .LUT_init_mode_in     (LUT_init_mode_in),
    .LUT_rd_address_in    (LUT_rd_address_in[13:0]),
    .LUT_rd_type_in       (LUT_rd_type_in),
    .LUT_rd_R_in          (LUT_rd_R14_in),
    .LUT_rd_Phi_in        (LUT_rd_Phi_in),
    .LUT_rd_data_out      (LUT_rd_data_out_14),
    .trig_SSC_BW      (trig_SSC14_BW),
    .trig_SSC         (trig_SSC14),
    .valid_SSC        (valid_SSC14),
    .Inner_decoded    (Inner_decoded_SSC14)
);
    
SSC SSC15(
    .CLK_in     (CLK_in),
    .CLK_Q40    (CLK_Q40),
    .CLK_320    (CLK_320),
    .reset_in   (reset_in),
    .BW_R       (BW_R15),
    .BW_Phi0    (BW_Phi3[11:6]),
    .BW_Phi1    (BW_Phi3[5:0]),
    .BW_Phi2    (6'b0),
    .BW_Phi3    (6'b0),
    .isAside    (isAside),
    .HotROIdef  (HotROIdef_SSC15),
    .NSW_0_in         (NSW_0_in),
    .NSW_1_in         (NSW_1_in),
    .NSW_2_in         (NSW_2_in),
    .NSW_3_in         (NSW_3_in),
    .Align_eta0_in    (Align_eta0_NSW_in),
    .Align_eta1_in    (Align_eta1_NSW_in),
    .Align_eta2_in    (Align_eta2_NSW_in),
    .Align_eta3_in    (Align_eta3_NSW_in),
    .Align_phi0_in    (Align_phi0_NSW_in),
    .Align_phi1_in    (Align_phi1_NSW_in),
    .Align_phi2_in    (Align_phi2_NSW_in),
    .Align_phi3_in    (Align_phi3_NSW_in),
    .Eta_sub          (Eta_sub_SSC15),
    .Phi_sub0         (Phi_sub0_NSW),
    .Phi_sub1         (Phi_sub1_NSW),
    .Phi_sub2         (Phi_sub2_NSW),
    .Phi_sub3         (Phi_sub3_NSW),
    .NSW0_data_error  (NSW0_data_error),
    .NSW1_data_error  (NSW1_data_error),
    .NSW2_data_error  (NSW2_data_error),
    .NSW3_data_error  (NSW3_data_error),
    .NSWdisable       (NSWdisableSSC[10]),
    .LUT_init_data_in     (LUT_init_data_in),
    .LUT_init_Address_in  (LUT_init_Address_in[13:0]),
    .LUT_init_flg_in      (LUT_init_flag_in),
    .LUT_init_type_in     (LUT_init_type_in),
    .LUT_init_R_in        (LUT_init_R15_in),
    .LUT_init_Phi_in      (LUT_init_Phi_in),
    .LUT_init_mode_in     (LUT_init_mode_in),
    .LUT_rd_address_in    (LUT_rd_address_in[13:0]),
    .LUT_rd_type_in       (LUT_rd_type_in),
    .LUT_rd_R_in          (LUT_rd_R15_in),
    .LUT_rd_Phi_in        (LUT_rd_Phi_in),
    .LUT_rd_data_out      (LUT_rd_data_out_15),
    .trig_SSC_BW      (trig_SSC15_BW),
    .trig_SSC         (trig_SSC15),
    .valid_SSC        (valid_SSC15),
    .Inner_decoded    (Inner_decoded_SSC15)
);
    
SSC SSC16(
    .CLK_in     (CLK_in),
    .CLK_Q40    (CLK_Q40),
    .CLK_320    (CLK_320),
    .reset_in   (reset_in),
    .BW_R       (BW_R16),
    .BW_Phi0    (BW_Phi3[11:6]),
    .BW_Phi1    (BW_Phi3[5:0]),
    .BW_Phi2    (6'b0),
    .BW_Phi3    (6'b0),
    .isAside    (isAside),
    .HotROIdef  (HotROIdef_SSC16),
    .NSW_0_in         (NSW_0_in),
    .NSW_1_in         (NSW_1_in),
    .NSW_2_in         (NSW_2_in),
    .NSW_3_in         (NSW_3_in),
    .Align_eta0_in    (Align_eta0_NSW_in),
    .Align_eta1_in    (Align_eta1_NSW_in),
    .Align_eta2_in    (Align_eta2_NSW_in),
    .Align_eta3_in    (Align_eta3_NSW_in),
    .Align_phi0_in    (Align_phi0_NSW_in),
    .Align_phi1_in    (Align_phi1_NSW_in),
    .Align_phi2_in    (Align_phi2_NSW_in),
    .Align_phi3_in    (Align_phi3_NSW_in),
    .Eta_sub          (Eta_sub_SSC16),
    .Phi_sub0         (Phi_sub0_NSW),
    .Phi_sub1         (Phi_sub1_NSW),
    .Phi_sub2         (Phi_sub2_NSW),
    .Phi_sub3         (Phi_sub3_NSW),
    .NSW0_data_error  (NSW0_data_error),
    .NSW1_data_error  (NSW1_data_error),
    .NSW2_data_error  (NSW2_data_error),
    .NSW3_data_error  (NSW3_data_error),
    .NSWdisable       (NSWdisableSSC[11]),
    .LUT_init_data_in     (LUT_init_data_in),
    .LUT_init_Address_in  (LUT_init_Address_in[13:0]),
    .LUT_init_flg_in      (LUT_init_flag_in),
    .LUT_init_type_in     (LUT_init_type_in),
    .LUT_init_R_in        (LUT_init_R16_in),
    .LUT_init_Phi_in      (LUT_init_Phi_in),
    .LUT_init_mode_in     (LUT_init_mode_in),
    .LUT_rd_address_in    (LUT_rd_address_in[13:0]),
    .LUT_rd_type_in       (LUT_rd_type_in),
    .LUT_rd_R_in          (LUT_rd_R16_in),
    .LUT_rd_Phi_in        (LUT_rd_Phi_in),
    .LUT_rd_data_out      (LUT_rd_data_out_16),
    .trig_SSC_BW      (trig_SSC16_BW),
    .trig_SSC         (trig_SSC16),
    .valid_SSC        (valid_SSC16),
    .Inner_decoded    (Inner_decoded_SSC16)
);
    
SSC SSC17(
    .CLK_in     (CLK_in),
    .CLK_Q40    (CLK_Q40),
    .CLK_320    (CLK_320),
    .reset_in   (reset_in),
    .BW_R       (BW_R17),
    .BW_Phi0    (BW_Phi3[11:6]),
    .BW_Phi1    (BW_Phi3[5:0]),
    .BW_Phi2    (6'b0),
    .BW_Phi3    (6'b0),
    .isAside    (isAside),
    .HotROIdef  (HotROIdef_SSC17),
    .NSW_0_in         (NSW_0_in),
    .NSW_1_in         (NSW_1_in),
    .NSW_2_in         (NSW_2_in),
    .NSW_3_in         (NSW_3_in),
    .Align_eta0_in    (Align_eta0_NSW_in),
    .Align_eta1_in    (Align_eta1_NSW_in),
    .Align_eta2_in    (Align_eta2_NSW_in),
    .Align_eta3_in    (Align_eta3_NSW_in),
    .Align_phi0_in    (Align_phi0_NSW_in),
    .Align_phi1_in    (Align_phi1_NSW_in),
    .Align_phi2_in    (Align_phi2_NSW_in),
    .Align_phi3_in    (Align_phi3_NSW_in),
    .Eta_sub          (Eta_sub_SSC17),
    .Phi_sub0         (Phi_sub0_NSW),
    .Phi_sub1         (Phi_sub1_NSW),
    .Phi_sub2         (Phi_sub2_NSW),
    .Phi_sub3         (Phi_sub3_NSW),
    .NSW0_data_error  (NSW0_data_error),
    .NSW1_data_error  (NSW1_data_error),
    .NSW2_data_error  (NSW2_data_error),
    .NSW3_data_error  (NSW3_data_error),
    .NSWdisable       (NSWdisableSSC[12]),
    .LUT_init_data_in     (LUT_init_data_in),
    .LUT_init_Address_in  (LUT_init_Address_in[13:0]),
    .LUT_init_flg_in      (LUT_init_flag_in),
    .LUT_init_type_in     (LUT_init_type_in),
    .LUT_init_R_in        (LUT_init_R17_in),
    .LUT_init_Phi_in      (LUT_init_Phi_in),
    .LUT_init_mode_in     (LUT_init_mode_in),
    .LUT_rd_address_in    (LUT_rd_address_in[13:0]),
    .LUT_rd_type_in       (LUT_rd_type_in),
    .LUT_rd_R_in          (LUT_rd_R17_in),
    .LUT_rd_Phi_in        (LUT_rd_Phi_in),
    .LUT_rd_data_out      (LUT_rd_data_out_17),
    .trig_SSC_BW      (trig_SSC17_BW),
    .trig_SSC         (trig_SSC17),
    .valid_SSC        (valid_SSC17),
    .Inner_decoded    (Inner_decoded_SSC17)
);
    
SSC SSC18(
    .CLK_in     (CLK_in),
    .CLK_Q40    (CLK_Q40),
    .CLK_320    (CLK_320),
    .reset_in   (reset_in),
    .BW_R       (BW_R18),
    .BW_Phi0    (BW_Phi3[11:6]),
    .BW_Phi1    (BW_Phi3[5:0]),
    .BW_Phi2    (6'b0),
    .BW_Phi3    (6'b0),
    .isAside    (isAside),
    .HotROIdef  (HotROIdef_SSC18),
    .NSW_0_in         (NSW_0_in),
    .NSW_1_in         (NSW_1_in),
    .NSW_2_in         (NSW_2_in),
    .NSW_3_in         (NSW_3_in),
    .Align_eta0_in    (Align_eta0_NSW_in),
    .Align_eta1_in    (Align_eta1_NSW_in),
    .Align_eta2_in    (Align_eta2_NSW_in),
    .Align_eta3_in    (Align_eta3_NSW_in),
    .Align_phi0_in    (Align_phi0_NSW_in),
    .Align_phi1_in    (Align_phi1_NSW_in),
    .Align_phi2_in    (Align_phi2_NSW_in),
    .Align_phi3_in    (Align_phi3_NSW_in),
    .Eta_sub          (Eta_sub_SSC18),
    .Phi_sub0         (Phi_sub0_NSW),
    .Phi_sub1         (Phi_sub1_NSW),
    .Phi_sub2         (Phi_sub2_NSW),
    .Phi_sub3         (Phi_sub3_NSW),
    .NSW0_data_error  (NSW0_data_error),
    .NSW1_data_error  (NSW1_data_error),
    .NSW2_data_error  (NSW2_data_error),
    .NSW3_data_error  (NSW3_data_error),
    .NSWdisable       (NSWdisableSSC[13]),
    .LUT_init_data_in     (LUT_init_data_in),
    .LUT_init_Address_in  (LUT_init_Address_in[13:0]),
    .LUT_init_flg_in      (LUT_init_flag_in),
    .LUT_init_type_in     (LUT_init_type_in),
    .LUT_init_R_in        (LUT_init_R18_in),
    .LUT_init_Phi_in      (LUT_init_Phi_in),
    .LUT_init_mode_in     (LUT_init_mode_in),
    .LUT_rd_address_in    (LUT_rd_address_in[13:0]),
    .LUT_rd_type_in       (LUT_rd_type_in),
    .LUT_rd_R_in          (LUT_rd_R18_in),
    .LUT_rd_Phi_in        (LUT_rd_Phi_in),
    .LUT_rd_data_out      (LUT_rd_data_out_18),
    .trig_SSC_BW      (trig_SSC18_BW),
    .trig_SSC         (trig_SSC18),
    .valid_SSC        (valid_SSC18),
    .Inner_decoded    (Inner_decoded_SSC18)
);
    

endmodule

