# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/smarumot/alveo_firm/kernel_design/fw_sl2/project_1/project_1.srcs/sources_1/ip/dcm40_to_160/dcm40_to_160.xci
# IP: The module: 'dcm40_to_160' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/smarumot/alveo_firm/kernel_design/fw_sl2/project_1/project_1.gen/sources_1/ip/dcm40_to_160/dcm40_to_160_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm40_to_160'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/smarumot/alveo_firm/kernel_design/fw_sl2/project_1/project_1.gen/sources_1/ip/dcm40_to_160/dcm40_to_160.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm40_to_160'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/smarumot/alveo_firm/kernel_design/fw_sl2/project_1/project_1.gen/sources_1/ip/dcm40_to_160/dcm40_to_160_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm40_to_160'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/smarumot/alveo_firm/kernel_design/fw_sl2/project_1/project_1.srcs/sources_1/ip/dcm40_to_160/dcm40_to_160.xci
# IP: The module: 'dcm40_to_160' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/smarumot/alveo_firm/kernel_design/fw_sl2/project_1/project_1.gen/sources_1/ip/dcm40_to_160/dcm40_to_160_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm40_to_160'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/smarumot/alveo_firm/kernel_design/fw_sl2/project_1/project_1.gen/sources_1/ip/dcm40_to_160/dcm40_to_160.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm40_to_160'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/smarumot/alveo_firm/kernel_design/fw_sl2/project_1/project_1.gen/sources_1/ip/dcm40_to_160/dcm40_to_160_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm40_to_160'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
