# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/smarumot/alveo_firm/kernel_design/fw_sl2/project_1/project_1.srcs/sources_1/ip/LUT_ptTDP_1/LUT_ptTDP.xci
# IP: The module: 'LUT_ptTDP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/smarumot/alveo_firm/kernel_design/fw_sl2/project_1/project_1.gen/sources_1/ip/LUT_ptTDP_1/LUT_ptTDP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LUT_ptTDP'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/smarumot/alveo_firm/kernel_design/fw_sl2/project_1/project_1.srcs/sources_1/ip/LUT_ptTDP_1/LUT_ptTDP.xci
# IP: The module: 'LUT_ptTDP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/smarumot/alveo_firm/kernel_design/fw_sl2/project_1/project_1.gen/sources_1/ip/LUT_ptTDP_1/LUT_ptTDP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LUT_ptTDP'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
